language: java

env:
  global:
  - MAVEN_OPTS="-Drevision=$(git describe --dirty --tags)-SNAPSHOT"

addons:
  sonarcloud:
    organization: "ianagbip1oti-github"

before_install:
- "[ -n \"$encrypted_aa77755bd8a1_key\" ] && openssl aes-256-cbc -K $encrypted_aa77755bd8a1_key -iv $encrypted_aa77755bd8a1_iv -in etc/codesigning.asc.enc -out etc/codesigning.asc -d"
- "[ -f etc/codesigning.asc ] && gpg --fast-import etc/codesigning.asc"

stages:
- build
- name: snapshot
  if: branch = master AND NOT type = pull_request
- name: release
  if: tag =~ ^\d+\.\d+\.\d+$
  
jobs:
  include:
    - stage: build
      jdk: oraclejdk8
      script: mvn -B verify
    - jdk: oraclejdk9
      script: mvn -B verify
    - jdk: openjdk8
      script: mvn -B verify
    - stage: snapshot
      jdk: openjdk8
      script: mvn -s etc/settings.xml -B deploy -P release
    - jdk: openjdk8
      script: mvn -B verify sonar:sonar
    - stage: release
      jdk: openjdk8
      env:
        - MAVEN_OPTS="-Drevision=$(git describe --dirty --tags)"
      script: mvn -s etc/settings.xml -B deploy -P release
    - jdk: openjdk8
      env:
        - MAVEN_OPTS="-Drevision=$(git describe --dirty --tags)"
      script: mvn -B site
      deploy:
        edge:
          branch: v1.8.47
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: target/site
        on:
          tags: true
    
